2020-12-21 18:33:45 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.308.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"products.json">>,reason => enoent},[{'Elixir.File','read!',1,[{file,"lib/file.ex"},{line,354}]},{'Elixir.CALC.Application',create_table,0,[{file,"lib/application.ex"},{line,25}]},{'Elixir.CALC.Application',start,2,[{file,"lib/application.ex"},{line,18}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.307.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.309.0>,normal}]
    links: [<0.307.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 217
  neighbours:
2020-12-21 18:34:11 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.285.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent},[{'Elixir.File','read!',1,[{file,"lib/file.ex"},{line,354}]},{'Elixir.CALC.Application',create_table,0,[{file,"lib/application.ex"},{line,25}]},{'Elixir.CALC.Application',start,2,[{file,"lib/application.ex"},{line,18}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.284.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.286.0>,normal}]
    links: [<0.284.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 217
  neighbours:
2020-12-21 18:36:01 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.285.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent},[{'Elixir.File','read!',1,[{file,"lib/file.ex"},{line,354}]},{'Elixir.CALC.Application',create_table,0,[{file,"lib/application.ex"},{line,26}]},{'Elixir.CALC.Application',start,2,[{file,"lib/application.ex"},{line,18}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.284.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.286.0>,normal}]
    links: [<0.284.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 225
  neighbours:
2020-12-21 18:36:52 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.285.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent},[{'Elixir.File','read!',1,[{file,"lib/file.ex"},{line,354}]},{'Elixir.CALC.Application',create_table,0,[{file,"lib/application.ex"},{line,27}]},{'Elixir.CALC.Application',start,2,[{file,"lib/application.ex"},{line,18}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.284.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.286.0>,normal}]
    links: [<0.284.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 237
  neighbours:
2020-12-21 18:39:54 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.285.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"/home/etienne/rabbitmq_project/_build/dev/lib/calc/lib/products.json">>,reason => enoent},[{'Elixir.File','read!',1,[{file,"lib/file.ex"},{line,354}]},{'Elixir.CALC.Application',create_table,0,[{file,"lib/application.ex"},{line,27}]},{'Elixir.CALC.Application',start,2,[{file,"lib/application.ex"},{line,18}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.284.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.286.0>,normal}]
    links: [<0.284.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 233
  neighbours:
2020-12-21 18:45:56 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {add,10}
** When Server state == #{amount => 10,key => <<"banane">>}
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.298.0>,#Ref<0.3563171291.904921091.196483>},#{amount => 10,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,18}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
** Client <0.298.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,280}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,265}]},{'Elixir.IEx.Evaluator',handle_eval,5,[{file,"lib/iex/evaluator.ex"},{line,261}]},{'Elixir.IEx.Evaluator',do_eval,3,[{file,"lib/iex/evaluator.ex"},{line,242}]},{'Elixir.IEx.Evaluator',eval,3,[{file,"lib/iex/evaluator.ex"},{line,220}]}]
2020-12-21 18:45:56 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.293.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.298.0>,#Ref<0.3563171291.904921091.196483>},#{amount => 10,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,18}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 7401
  neighbours:
2020-12-21 18:45:56 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.298.0>,#Ref<0.3563171291.904921091.196483>},#{amount => 10,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,18}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.293.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 18:48:15 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {'$gen_cast',{add,10}}
** When Server state == #{amount => 10,key => <<"banane">>}
** Reason for termination ==
** {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 18:48:15 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.294.0>
    registered_name: []
    exception error: {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3591
  neighbours:
2020-12-21 18:48:15 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.294.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 18:52:24 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {'$gen_cast',{add,10}}
** When Server state == #{amount => 10,key => <<"banane">>}
** Reason for termination ==
** {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 18:52:24 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.294.0>
    registered_name: []
    exception error: {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3611
  neighbours:
2020-12-21 18:52:24 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.294.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 18:57:03 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {'$gen_cast',{add,10}}
** When Server state == #{amount => 10,key => <<"banane">>}
** Reason for termination ==
** {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 18:57:03 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.279.0>
    registered_name: []
    exception error: {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.272.0>]
    message_queue_len: 0
    messages: []
    links: [<0.274.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3532
  neighbours:
2020-12-21 18:57:03 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.279.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 19:00:05 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {'$gen_cast',{add,10}}
** When Server state == #{amount => 10,key => <<"banane">>}
** Reason for termination ==
** {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 19:00:05 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.294.0>
    registered_name: []
    exception error: {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3647
  neighbours:
2020-12-21 19:00:05 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>},[{'Elixir.CALC.Agent',handle_cast,2,[{file,"lib/gen_server.ex"},{line,822}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.294.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 19:51:50 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    start_error
     Reason:     {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]}]}}
     Offender:   [{pid,undefined},{id,<<"resupply">>},{mfargs,{'Elixir.CALC.Resupply',start,[]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 19:51:50 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.298.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{noproc,{'Elixir.GenServer',call,['Elixir.CALC.AgentSupervisor',{start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}},infinity]}}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.297.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.299.0>,normal}]
    links: [<0.297.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 219
  neighbours:
2020-12-21 19:53:35 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    start_error
     Reason:     {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]}]}}
     Offender:   [{pid,undefined},{id,<<"resupply">>},{mfargs,{'Elixir.CALC.Resupply',start,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 19:53:35 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.297.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{noproc,{'Elixir.GenServer',call,['Elixir.CALC.AgentSupervisor',{start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}},infinity]}}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.296.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.298.0>,normal}]
    links: [<0.296.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 219
  neighbours:
2020-12-21 19:56:16 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    start_error
     Reason:     {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]}]}}
     Offender:   [{pid,undefined},{id,1},{mfargs,{'Elixir.CALC.Resupply',start,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 19:56:16 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.285.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{noproc,{'Elixir.GenServer',call,['Elixir.CALC.AgentSupervisor',{start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}},infinity]}}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.284.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.286.0>,normal}]
    links: [<0.284.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 219
  neighbours:
2020-12-21 19:56:44 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    start_error
     Reason:     {'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]}]}}
     Offender:   [{pid,undefined},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 19:56:44 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.285.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{noproc,{'Elixir.GenServer',call,['Elixir.CALC.AgentSupervisor',{start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}},infinity]}}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.284.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.286.0>,normal}]
    links: [<0.284.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 219
  neighbours:
2020-12-21 20:00:16 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    start_error
     Reason:     {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]}]}}
     Offender:   [{pid,undefined},{id,<<"resupply">>},{mfargs,{'Elixir.CALC.Resupply',start,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 20:00:16 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.285.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,{shutdown,{failed_to_start_child,<<"resupply">>,{'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]}]}}}}}},[{'Elixir.String.Chars','impl_for!',1,[{file,"lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"lib/string/chars.ex"},{line,22}]},{'Elixir.IO',puts,2,[{file,"lib/io.ex"},{line,686}]},{'Elixir.CALC.Application',start,2,[{file,"lib/application.ex"},{line,19}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.284.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.286.0>,normal}]
    links: [<0.284.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 28
    reductions: 261
  neighbours:
2020-12-21 20:01:48 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    start_error
     Reason:     {'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]}]}}
     Offender:   [{pid,undefined},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 20:01:48 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.285.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,{shutdown,{failed_to_start_child,'Elixir.CALC.Resupply',{'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]}]}}}}}},[{'Elixir.String.Chars','impl_for!',1,[{file,"lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"lib/string/chars.ex"},{line,22}]},{'Elixir.IO',puts,2,[{file,"lib/io.ex"},{line,686}]},{'Elixir.CALC.Application',start,2,[{file,"lib/application.ex"},{line,19}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.284.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.286.0>,normal}]
    links: [<0.284.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 28
    reductions: 261
  neighbours:
2020-12-21 20:02:22 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.286.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<0.288.0>}},[{'Elixir.String.Chars','impl_for!',1,[{file,"lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"lib/string/chars.ex"},{line,22}]},{'Elixir.IO',puts,2,[{file,"lib/io.ex"},{line,686}]},{'Elixir.CALC.Application',start,2,[{file,"lib/application.ex"},{line,19}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.285.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.287.0>,normal}]
    links: [<0.285.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 224
  neighbours:
2020-12-21 20:06:10 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {resupply,<0.295.0>}
** When Server state == []
** Reason for termination ==
** {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
** Client <0.295.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{'Elixir.CALC.Agent',handle_call,3,[{file,"lib/agent.ex"},{line,27}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]
2020-12-21 20:06:10 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.289.0>
    registered_name: []
    exception error: {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 0
    messages: []
    links: [<0.287.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5492
  neighbours:
2020-12-21 20:06:10 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.289.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 20:06:10 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {remove,9}
** When Server state == #{amount => 10,key => <<"banane">>}
** Reason for termination ==
** {{{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},5000]}},[{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1027}]},{'Elixir.CALC.Agent',handle_call,3,[{file,"lib/agent.ex"},{line,27}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
** Client <0.300.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,280}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,265}]},{'Elixir.IEx.Evaluator',handle_eval,5,[{file,"lib/iex/evaluator.ex"},{line,261}]},{'Elixir.IEx.Evaluator',do_eval,3,[{file,"lib/iex/evaluator.ex"},{line,242}]},{'Elixir.IEx.Evaluator',eval,3,[{file,"lib/iex/evaluator.ex"},{line,220}]}]
2020-12-21 20:06:10 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.295.0>
    registered_name: []
    exception exit: {{{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},5000]}},[{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1027}]},{'Elixir.CALC.Agent',handle_call,3,[{file,"lib/agent.ex"},{line,27}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 8887
  neighbours:
2020-12-21 20:06:10 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},5000]}}
     Offender:   [{pid,<0.295.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 20:07:25 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',{resupply,<0.296.0>}}
** When Server state == []
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.296.0>},[]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 20:07:25 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.290.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.296.0>},[]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3528
  neighbours:
2020-12-21 20:07:25 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.296.0>},[]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.290.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 20:13:46 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',{resupply,<0.296.0>}}
** When Server state == []
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.296.0>},[]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 20:13:46 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.290.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.296.0>},[]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3558
  neighbours:
2020-12-21 20:13:46 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.296.0>},[]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.290.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 20:15:04 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {add,10}
** When Server state == #{amount => 1,key => <<"banane">>}
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
** Client <0.290.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,22}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]
2020-12-21 20:15:04 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.296.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 28
    reductions: 6826
  neighbours:
2020-12-21 20:15:04 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.296.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 20:15:04 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',go}
** When Server state == [<0.296.0>]
** Reason for termination ==
** {{{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}},[{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1027}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,22}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 20:15:04 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.290.0>
    registered_name: []
    exception exit: {{{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}},[{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1027}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,22}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 6339
  neighbours:
2020-12-21 20:15:04 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}}
     Offender:   [{pid,<0.290.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 21:23:55 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',{resupply,<0.298.0>}}
** When Server state == [<0.300.0>|<0.297.0>]
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.298.0>},[<0.300.0>|<0.297.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 21:23:55 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.290.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.298.0>},[<0.300.0>|<0.297.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 3
    messages: [{'$gen_cast',{resupply,<0.300.0>}},{'$gen_cast',{resupply,<0.299.0>}},{'$gen_cast',{resupply,<0.296.0>}}]
    links: [<0.287.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3835
  neighbours:
2020-12-21 21:23:55 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.298.0>},[<0.300.0>|<0.297.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.290.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 21:25:02 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',go}
** When Server state == [[[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>]|<0.300.0>]
** Reason for termination ==
** {function_clause,[{'Elixir.GenServer',cast,[[[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>],{add,10}],[{file,"lib/gen_server.ex"},{line,1058}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,20}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 21:25:02 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.291.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.GenServer',cast,[[[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>],{add,10}],[{file,"lib/gen_server.ex"},{line,1058}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,20}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5041
  neighbours:
2020-12-21 21:25:02 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.GenServer',cast,[[[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>],{add,10}],[{file,"lib/gen_server.ex"},{line,1058}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,20}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.291.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 21:26:21 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',{resupply,<0.303.0>}}
** When Server state == [<0.304.0>|<0.305.0>]
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.303.0>},[<0.304.0>|<0.305.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 21:26:21 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.297.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.303.0>},[<0.304.0>|<0.305.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.293.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3751
  neighbours:
2020-12-21 21:26:21 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.303.0>},[<0.304.0>|<0.305.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.297.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 21:26:27 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',{resupply,<0.306.0>}}
** When Server state == [<0.305.0>|<0.307.0>]
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.306.0>},[<0.305.0>|<0.307.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 21:26:27 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.308.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.306.0>},[<0.305.0>|<0.307.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.293.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3614
  neighbours:
2020-12-21 21:26:27 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.306.0>},[<0.305.0>|<0.307.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.308.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 21:29:03 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',{resupply,<0.299.0>}}
** When Server state == [<0.301.0>|<0.297.0>]
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.299.0>},[<0.301.0>|<0.297.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 21:29:03 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.291.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.299.0>},[<0.301.0>|<0.297.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3727
  neighbours:
2020-12-21 21:29:03 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.299.0>},[<0.301.0>|<0.297.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.291.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 21:29:07 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',{resupply,<0.301.0>}}
** When Server state == [<0.300.0>|<0.298.0>]
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.301.0>},[<0.300.0>|<0.298.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 21:29:07 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.302.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.301.0>},[<0.300.0>|<0.298.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3590
  neighbours:
2020-12-21 21:29:07 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.301.0>},[<0.300.0>|<0.298.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.302.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 21:29:07 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',{resupply,<0.298.0>}}
** When Server state == [<0.299.0>|<0.297.0>]
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.298.0>},[<0.299.0>|<0.297.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 21:29:07 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.304.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.298.0>},[<0.299.0>|<0.297.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3590
  neighbours:
2020-12-21 21:29:07 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Resupply',handle_cast,[{resupply,<0.298.0>},[<0.299.0>|<0.297.0>]],[{file,"lib/resupply.ex"},{line,14}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.304.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 21:29:49 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',{resupply,<0.299.0>}}
** When Server state == [<0.301.0>|<0.300.0>]
** Reason for termination ==
** {badarg,[{erlang,'++',[[<0.301.0>|<0.300.0>],<0.299.0>],[]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,18}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 21:29:49 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.291.0>
    registered_name: []
    exception error: bad argument: [{erlang,'++',[[<0.301.0>|<0.300.0>],<0.299.0>],[]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,18}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]
    ancestors: ['Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3843
  neighbours:
2020-12-21 21:29:49 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {badarg,[{erlang,'++',[[<0.301.0>|<0.300.0>],<0.299.0>],[]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,18}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.291.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 21:29:51 =ERROR REPORT====
** Generic server resupply terminating 
** Last message in was {'$gen_cast',{resupply,<0.298.0>}}
** When Server state == [<0.300.0>|<0.301.0>]
** Reason for termination ==
** {badarg,[{erlang,'++',[[<0.300.0>|<0.301.0>],<0.298.0>],[]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,18}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-21 21:29:51 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Resupply:init/1
    pid: <0.302.0>
    registered_name: []
    exception error: bad argument: [{erlang,'++',[[<0.300.0>|<0.301.0>],<0.298.0>],[]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,18}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]
    ancestors: ['Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 3705
  neighbours:
2020-12-21 21:29:51 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.MainSupervisor'}
     Context:    child_terminated
     Reason:     {badarg,[{erlang,'++',[[<0.300.0>|<0.301.0>],<0.298.0>],[]},{'Elixir.CALC.Resupply',handle_cast,2,[{file,"lib/resupply.ex"},{line,18}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.302.0>},{id,'Elixir.CALC.Resupply'},{mfargs,{'Elixir.CALC.Resupply',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-21 22:09:46 =ERROR REPORT====
** Generic server poire_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"poire">>,resupplied => true,resupply_pid => <0.296.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:09:46 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.305.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5513
  neighbours:
2020-12-21 22:09:46 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.305.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"poire">>,10,<0.296.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:09:46 =ERROR REPORT====
** Generic server framboise_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"framboise">>,resupplied => true,resupply_pid => <0.296.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:09:46 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.303.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:09:46 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.303.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"framboise">>,10,<0.296.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:09:46 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"banane">>,resupplied => true,resupply_pid => <0.296.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:09:46 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.302.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:09:46 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.302.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10,<0.296.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:09:46 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"peche">>,resupplied => true,resupply_pid => <0.296.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:09:46 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.306.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:09:46 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.306.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.296.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:09:46 =ERROR REPORT====
** Generic server pomme_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"pomme">>,resupplied => true,resupply_pid => <0.296.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:09:46 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.304.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:09:46 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.304.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"pomme">>,10,<0.296.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:14:32 =ERROR REPORT====
** Generic server pomme_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"pomme">>,resupplied => true,resupply_pid => <0.290.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:14:32 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.298.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5519
  neighbours:
2020-12-21 22:14:32 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.298.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"pomme">>,10,<0.290.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:14:32 =ERROR REPORT====
** Generic server poire_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"poire">>,resupplied => true,resupply_pid => <0.290.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:14:32 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.299.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:14:32 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.299.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"poire">>,10,<0.290.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:14:32 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {remove,3}
** When Server state == #{amount => 10,key => <<"banane">>,resupplied => true,resupply_pid => <0.290.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:14:32 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.296.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:14:32 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.296.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10,<0.290.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:16:41 =ERROR REPORT====
** Generic server poire_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"poire">>,resupplied => true,resupply_pid => <0.296.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:16:41 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.305.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5403
  neighbours:
2020-12-21 22:16:41 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.305.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"poire">>,10,<0.296.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:16:41 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"peche">>,resupplied => true,resupply_pid => <0.296.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:16:41 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.306.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5095
  neighbours:
2020-12-21 22:16:41 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.306.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.296.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:16:41 =ERROR REPORT====
** Generic server framboise_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"framboise">>,resupplied => true,resupply_pid => <0.296.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:16:41 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.303.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5116
  neighbours:
2020-12-21 22:16:41 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.303.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"framboise">>,10,<0.296.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:16:41 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {remove,3}
** When Server state == #{amount => 10,key => <<"banane">>,resupplied => true,resupply_pid => <0.296.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:16:41 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.302.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5108
  neighbours:
2020-12-21 22:16:41 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.302.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10,<0.296.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:19:54 =ERROR REPORT====
** Generic server poire_agent terminating 
** Last message in was {remove,3}
** When Server state == #{amount => 10,key => <<"poire">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:19:54 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.300.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5813
  neighbours:
2020-12-21 22:19:54 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.300.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"poire">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:19:54 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"peche">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:19:54 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.301.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:19:54 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.301.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:19:54 =ERROR REPORT====
** Generic server framboise_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"framboise">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:19:54 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.298.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:19:54 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.298.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"framboise">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:20:51 =ERROR REPORT====
** Generic server poire_agent terminating 
** Last message in was {remove,3}
** When Server state == #{amount => 10,key => <<"poire">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:20:51 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.300.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5789
  neighbours:
2020-12-21 22:20:51 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.300.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"poire">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:20:51 =ERROR REPORT====
** Generic server framboise_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"framboise">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:20:51 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.298.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:20:51 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.298.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"framboise">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:20:51 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"peche">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:20:51 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.301.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:20:51 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.301.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:21:10 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"banane">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:21:10 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.297.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5787
  neighbours:
2020-12-21 22:21:10 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.297.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:21:10 =ERROR REPORT====
** Generic server pomme_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"pomme">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:21:10 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.299.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:21:10 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.299.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"pomme">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:21:10 =ERROR REPORT====
** Generic server framboise_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"framboise">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:21:10 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.298.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:21:10 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.298.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"framboise">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:21:10 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"peche">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:21:10 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.301.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5377
  neighbours:
2020-12-21 22:21:10 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.301.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:22:36 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"peche">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:22:36 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.301.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5650
  neighbours:
2020-12-21 22:22:36 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.301.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:22:36 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {remove,3}
** When Server state == #{amount => 10,key => <<"banane">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:22:36 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.297.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5665
  neighbours:
2020-12-21 22:22:36 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.297.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:22:36 =ERROR REPORT====
** Generic server pomme_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"pomme">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:22:36 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.299.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5665
  neighbours:
2020-12-21 22:22:36 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.299.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"pomme">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:23:43 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"banane">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:23:43 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.297.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5619
  neighbours:
2020-12-21 22:23:43 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.297.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:23:43 =ERROR REPORT====
** Generic server poire_agent terminating 
** Last message in was {remove,3}
** When Server state == #{amount => 10,key => <<"poire">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:23:43 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.300.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5645
  neighbours:
2020-12-21 22:23:43 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.300.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"poire">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:23:43 =ERROR REPORT====
** Generic server pomme_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"pomme">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:23:43 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.299.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5645
  neighbours:
2020-12-21 22:23:43 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.299.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"pomme">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:23:43 =ERROR REPORT====
** Generic server framboise_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"framboise">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:23:43 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.298.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5636
  neighbours:
2020-12-21 22:23:43 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.298.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"framboise">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:23:43 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"peche">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:23:43 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.301.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5645
  neighbours:
2020-12-21 22:23:43 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.301.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:24:31 =ERROR REPORT====
** Generic server framboise_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"framboise">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:24:31 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.298.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5662
  neighbours:
2020-12-21 22:24:31 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.298.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"framboise">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:24:31 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"peche">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:24:31 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.301.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5657
  neighbours:
2020-12-21 22:24:31 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.301.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:26:22 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"banane">>,resupplied => true,resupply_pid => <0.290.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:26:22 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.296.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5637
  neighbours:
2020-12-21 22:26:22 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.296.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10,<0.290.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:26:22 =ERROR REPORT====
** Generic server poire_agent terminating 
** Last message in was {remove,3}
** When Server state == #{amount => 10,key => <<"poire">>,resupplied => true,resupply_pid => <0.290.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:26:22 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.299.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5657
  neighbours:
2020-12-21 22:26:22 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.299.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"poire">>,10,<0.290.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:26:22 =ERROR REPORT====
** Generic server pomme_agent terminating 
** Last message in was {remove,3}
** When Server state == #{amount => 10,key => <<"pomme">>,resupplied => true,resupply_pid => <0.290.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:26:22 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.298.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5657
  neighbours:
2020-12-21 22:26:22 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.298.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"pomme">>,10,<0.290.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:26:22 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"peche">>,resupplied => true,resupply_pid => <0.290.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:26:22 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.300.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.286.0>]
    message_queue_len: 0
    messages: []
    links: [<0.288.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5657
  neighbours:
2020-12-21 22:26:22 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.300.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.290.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:28:56 =ERROR REPORT====
** Generic server poire_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"poire">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:28:56 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.300.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5658
  neighbours:
2020-12-21 22:28:56 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.300.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"poire">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:28:56 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"banane">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:28:56 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.297.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5661
  neighbours:
2020-12-21 22:28:56 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.297.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:28:56 =ERROR REPORT====
** Generic server pomme_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"pomme">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:28:56 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.299.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5651
  neighbours:
2020-12-21 22:28:56 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.299.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"pomme">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:28:56 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {remove,3}
** When Server state == #{amount => 10,key => <<"peche">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:28:56 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.301.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5651
  neighbours:
2020-12-21 22:28:56 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.301.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:29:46 =ERROR REPORT====
** Generic server framboise_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"framboise">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:29:46 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.298.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5692
  neighbours:
2020-12-21 22:29:46 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.298.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"framboise">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:29:46 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {remove,2}
** When Server state == #{amount => 10,key => <<"banane">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:29:46 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.297.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5680
  neighbours:
2020-12-21 22:29:46 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.297.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:29:46 =ERROR REPORT====
** Generic server pomme_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"pomme">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:29:46 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.299.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5680
  neighbours:
2020-12-21 22:29:46 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.299.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"pomme">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 22:29:46 =ERROR REPORT====
** Generic server poire_agent terminating 
** Last message in was {remove,1}
** When Server state == #{amount => 10,key => <<"poire">>,resupplied => true,resupply_pid => <0.291.0>}
** Reason for termination ==
** {bad_return_value,nil}
** Client 'Elixir.CALC.OrderSupervisor' stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1024}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{'Elixir.CALC.Order',work,1,[{file,"lib/order.ex"},{line,9}]},{'Elixir.DynamicSupervisor',start_child,3,[{file,"lib/dynamic_supervisor.ex"},{line,693}]},{'Elixir.DynamicSupervisor',handle_start_child,2,[{file,"lib/dynamic_supervisor.ex"},{line,679}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]}]
2020-12-21 22:29:46 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.300.0>
    registered_name: []
    exception exit: {{bad_return_value,nil},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5680
  neighbours:
2020-12-21 22:29:46 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {bad_return_value,nil}
     Offender:   [{pid,<0.300.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"poire">>,10,<0.291.0>]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-21 23:17:16 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.282.0>
    registered_name: []
    exception error: {{badmatch,2},[{'Elixir.CALC.Agent',init,1,[{file,"lib/agent.ex"},{line,11}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.272.0>]
    message_queue_len: 0
    messages: []
    links: [<0.274.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 698
  neighbours:
2020-12-21 23:17:16 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.283.0>
    registered_name: []
    exception error: {{badmatch,2},[{'Elixir.CALC.Agent',init,1,[{file,"lib/agent.ex"},{line,11}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.272.0>]
    message_queue_len: 0
    messages: []
    links: [<0.274.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 693
  neighbours:
2020-12-21 23:17:16 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.284.0>
    registered_name: []
    exception error: {{badmatch,2},[{'Elixir.CALC.Agent',init,1,[{file,"lib/agent.ex"},{line,11}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.272.0>]
    message_queue_len: 0
    messages: []
    links: [<0.274.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 692
  neighbours:
2020-12-21 23:17:16 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.285.0>
    registered_name: []
    exception error: {{badmatch,2},[{'Elixir.CALC.Agent',init,1,[{file,"lib/agent.ex"},{line,11}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.272.0>]
    message_queue_len: 0
    messages: []
    links: [<0.274.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 692
  neighbours:
2020-12-21 23:17:16 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.286.0>
    registered_name: []
    exception error: {{badmatch,2},[{'Elixir.CALC.Agent',init,1,[{file,"lib/agent.ex"},{line,11}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.272.0>]
    message_queue_len: 0
    messages: []
    links: [<0.274.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 692
  neighbours:
2020-12-22 14:32:18 =ERROR REPORT====
** Generic server peche_agent terminating 
** Last message in was {continue,{check_notif,10}}
** When Server state == #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"peche">>,resupplied => true,resupply_pid => <0.306.0>}
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"peche">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-22 14:32:18 =ERROR REPORT====
** Generic server framboise_agent terminating 
** Last message in was {continue,{check_notif,10}}
** When Server state == #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"framboise">>,resupplied => true,resupply_pid => <0.306.0>}
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"framboise">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-22 14:32:18 =ERROR REPORT====
** Generic server banane_agent terminating 
** Last message in was {continue,{check_notif,10}}
** When Server state == #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"banane">>,resupplied => true,resupply_pid => <0.306.0>}
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"banane">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-22 14:32:18 =ERROR REPORT====
** Generic server poire_agent terminating 
** Last message in was {continue,{check_notif,10}}
** When Server state == #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"poire">>,resupplied => true,resupply_pid => <0.306.0>}
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"poire">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-22 14:32:18 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.315.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"poire">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.304.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5809
  neighbours:
2020-12-22 14:32:18 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.316.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"peche">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.304.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 28
    reductions: 6203
  neighbours:
2020-12-22 14:32:18 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.312.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"banane">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.304.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5831
  neighbours:
2020-12-22 14:32:18 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.313.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"framboise">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.304.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 28
    reductions: 6256
  neighbours:
2020-12-22 14:32:18 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"poire">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.315.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"poire">>,10,<0.306.0>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>}]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-22 14:32:18 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"peche">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.316.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"peche">>,10,<0.306.0>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>}]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-22 14:32:18 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"banane">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.312.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"banane">>,10,<0.306.0>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>}]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-22 14:32:18 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"framboise">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.313.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"framboise">>,10,<0.306.0>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>}]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-22 14:32:19 =ERROR REPORT====
** Generic server pomme_agent terminating 
** Last message in was {continue,{check_notif,10}}
** When Server state == #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"pomme">>,resupplied => true,resupply_pid => <0.306.0>}
** Reason for termination ==
** {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"pomme">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2020-12-22 14:32:19 =CRASH REPORT====
  crasher:
    initial call: Elixir.CALC.Agent:init/1
    pid: <0.314.0>
    registered_name: []
    exception error: {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"pomme">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: ['Elixir.CALC.AgentSupervisor','Elixir.CALC.MainSupervisor',<0.287.0>]
    message_queue_len: 0
    messages: []
    links: [<0.304.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 5909
  neighbours:
2020-12-22 14:32:19 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.AgentSupervisor'}
     Context:    child_terminated
     Reason:     {function_clause,[{'Elixir.CALC.Agent',handle_continue,[{check_notif,10},#{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>},key => <<"pomme">>,resupplied => true,resupply_pid => <0.306.0>}],[{file,"lib/agent.ex"},{line,47}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,loop,7,[{file,"gen_server.erl"},{line,431}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
     Offender:   [{pid,<0.314.0>},{id,undefined},{mfargs,{'Elixir.CALC.Agent',start,[<<"pomme">>,10,<0.306.0>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},custom_consumer => nil,pid => <0.301.0>}]}},{restart_type,transient},{shutdown,5000},{child_type,worker}]

2020-12-22 15:24:18 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.ClientSupervisor'}
     Context:    start_error
     Reason:     {'EXIT',{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'calc_exchange' in vhost '/'">>}},{gen_server,call,[<0.308.0>,{subscribe,{'basic.consume',0,<<"calc_exchange">>,<<>>,false,true,false,false,[]},<0.310.0>},60000]}}}
     Offender:   [{pid,undefined},{id,<<"clientTest">>},{mfargs,{'Elixir.CALC.Client',init,[<<"toto">>,[<<"peche.5">>]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-22 15:24:18 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.292.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,<<"clientTest">>,{'EXIT',{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'calc_exchange' in vhost '/'">>}},{gen_server,call,[<0.308.0>,{subscribe,{'basic.consume',0,<<"calc_exchange">>,<<>>,false,true,false,false,[]},<0.310.0>},60000]}}}}},{'Elixir.CALC.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.291.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.293.0>,normal}]
    links: [<0.291.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 221
  neighbours:
2020-12-22 15:24:29 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.ClientSupervisor'}
     Context:    start_error
     Reason:     {'EXIT',{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'calc_exchange' in vhost '/'">>}},{gen_server,call,[<0.293.0>,{subscribe,{'basic.consume',0,<<"calc_exchange">>,<<>>,false,true,false,false,[]},<0.295.0>},60000]}}}
     Offender:   [{pid,undefined},{id,<<"clientTest">>},{mfargs,{'Elixir.CALC.Client',init,[<<"toto">>,[<<"peche.5">>]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-22 15:24:29 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.277.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,<<"clientTest">>,{'EXIT',{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'calc_exchange' in vhost '/'">>}},{gen_server,call,[<0.293.0>,{subscribe,{'basic.consume',0,<<"calc_exchange">>,<<>>,false,true,false,false,[]},<0.295.0>},60000]}}}}},{'Elixir.CALC.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.276.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.278.0>,normal}]
    links: [<0.276.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 225
  neighbours:
2020-12-22 16:32:55 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.291.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>},[{'Elixir.Supervisor',init_child,1,[{file,"lib/supervisor.ex"},{line,631}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1399}]},{'Elixir.Supervisor',init,2,[{file,"lib/supervisor.ex"},{line,617}]},{'Elixir.Supervisor',start_link,2,[{file,"lib/supervisor.ex"},{line,556}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.290.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: [<0.290.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 28
    reductions: 446
  neighbours:
2020-12-22 16:36:03 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.291.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>},[{'Elixir.Supervisor',init_child,1,[{file,"lib/supervisor.ex"},{line,631}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1399}]},{'Elixir.Supervisor',init,2,[{file,"lib/supervisor.ex"},{line,617}]},{'Elixir.Supervisor',start_link,2,[{file,"lib/supervisor.ex"},{line,556}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.290.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: [<0.290.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 28
    reductions: 446
  neighbours:
2020-12-22 16:38:11 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.291.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>},[{'Elixir.Supervisor',init_child,1,[{file,"lib/supervisor.ex"},{line,631}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1399}]},{'Elixir.Supervisor',init,2,[{file,"lib/supervisor.ex"},{line,617}]},{'Elixir.Supervisor',start_link,2,[{file,"lib/supervisor.ex"},{line,556}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.290.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: [<0.290.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 28
    reductions: 446
  neighbours:
2020-12-22 16:40:26 =CRASH REPORT====
  crasher:
    initial call: supervisor:ok/1
    pid: <0.293.0>
    registered_name: []
    exception error: {undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.292.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 28
    reductions: 242
  neighbours:
2020-12-22 16:40:26 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.291.0>
    registered_name: []
    exception exit: {{{undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.CALC.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.290.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: [<0.290.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 462
  neighbours:
2020-12-22 16:41:06 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.291.0>
    registered_name: []
    exception exit: {{{undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.CALC.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.290.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: [<0.290.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 467
  neighbours:
2020-12-22 16:41:06 =CRASH REPORT====
  crasher:
    initial call: supervisor:ok/1
    pid: <0.293.0>
    registered_name: []
    exception error: {undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.292.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 28
    reductions: 242
  neighbours:
2020-12-22 16:45:16 =CRASH REPORT====
  crasher:
    initial call: supervisor:ok/1
    pid: <0.293.0>
    registered_name: []
    exception error: {undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.292.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 28
    reductions: 242
  neighbours:
2020-12-22 16:45:16 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.291.0>
    registered_name: []
    exception exit: {{{undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.CALC.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.290.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: [<0.290.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 339
  neighbours:
2020-12-22 17:17:08 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-e7mRKZCZ5lzAvRQJ3VS15Q">>}}
2020-12-22 17:17:08 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-ZDWJ4j_Y1F_jNcpVnKPJ7Q">>}}
2020-12-22 17:17:08 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-NULE9VqCrk0lObFBA0H2hg">>}}
2020-12-22 17:17:08 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-7ukL10Qrmn10b-78j9w4Tg">>}}
2020-12-22 17:17:08 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-VWRuHMr5N0xLCjDOjzCJMw">>}}
2020-12-22 17:25:43 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-rgcjzJ6QmtCIuKnKPPXEWw">>}}
2020-12-22 17:25:43 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-LzP_YmXhAg914_QIQZnM2Q">>}}
2020-12-22 17:25:43 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-lrWMukaTLbnkCM6dspy8hQ">>}}
2020-12-22 17:25:43 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-H-fuq4ATEAldHhqUZ2pQuQ">>}}
2020-12-22 17:25:43 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-w1x7xTBhqlH2u1WCpwxbYw">>}}
2020-12-22 17:27:20 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-n8onPFjX_NV93E1nrL1SfA">>}}
2020-12-22 17:27:20 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-x8BKSY2A7FPTV5HTggl7LQ">>}}
2020-12-22 17:27:20 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-fpF5-yZftk1edZ0V2qgrZg">>}}
2020-12-22 17:27:20 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-ZIDiIC3tlyDcHi4MtJsJkw">>}}
2020-12-22 17:27:20 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-v83aa3mCvnRiv7F2uEZ14Q">>}}
2020-12-22 17:28:26 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.CALC.ClientSupervisor'}
     Context:    start_error
     Reason:     {'EXIT',{{badmatch,<0.311.0>},[{'Elixir.CALC.Client',init,2,[{file,"lib/client.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]}]}}
     Offender:   [{pid,undefined},{id,<<"1">>},{mfargs,{'Elixir.CALC.Client',init,[<<"client_1">>,[<<"framboise.0">>]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2020-12-22 17:28:26 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.292.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,<<"1">>,{'EXIT',{{badmatch,<0.311.0>},[{'Elixir.CALC.Client',init,2,[{file,"lib/client.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]}]}}}},{'Elixir.CALC.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.291.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.293.0>,normal}]
    links: [<0.291.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 28
    reductions: 254
  neighbours:
2020-12-22 17:29:26 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-3t75e0uGpHbL7fLwMeKclg">>}}
2020-12-22 17:29:26 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-5FtIXQQDICaL65arC3ASCw">>}}
2020-12-22 17:29:26 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-qgNJBOs0sPXbhJRoI6jGQw">>}}
2020-12-22 17:29:26 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-31OLQvu0VMPjBJn2aFKMFA">>}}
2020-12-22 17:29:26 =ERROR REPORT====
Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-owt3xyssdHFF3e4yc6Fjyg">>}}
2020-12-22 18:42:03 =ERROR REPORT====
** Generic server <0.334.0> terminating 
** Last message in was socket_closed
** When Server state == {state,amqp_network_connection,{state,#Port<0.13>,<<"client 172.17.0.1:58109 -> 172.17.0.2:5672">>,10,<0.354.0>,131072,<0.333.0>,undefined,false},<0.351.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]},2047,[{<<"capabilities">>,table,[{<<"publisher_confirms">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"basic.nack">>,bool,true},{<<"consumer_cancel_notify">>,bool,true},{<<"connection.blocked">>,bool,true},{<<"consumer_priorities">>,bool,true},{<<"authentication_failure_close">>,bool,true},{<<"per_consumer_qos">>,bool,true},{<<"direct_reply_to">>,bool,true}]},{<<"cluster_name">>,longstr,<<"rabbit@my-rabbit">>},{<<"copyright">>,longstr,<<"Copyright (c) 2007-2020 VMware, Inc. or its affiliates.">>},{<<"information">>,longstr,<<"Licensed under the MPL 2.0. Website: https://rabbitmq.com">>},{<<"platform">>,longstr,<<"Erlang/OTP 23.0.3">>},{<<"product">>,longstr,<<"RabbitMQ">>},{<<"version">>,longstr,<<"3.8.6">>}],none,false}
** Reason for termination ==
** socket_closed_unexpectedly
2020-12-22 18:42:03 =ERROR REPORT====
** Generic server <0.337.0> terminating 
** Last message in was socket_closed
** When Server state == {state,amqp_network_connection,{state,#Port<0.11>,<<"client 172.17.0.1:38357 -> 172.17.0.2:5672">>,10,<0.355.0>,131072,<0.336.0>,undefined,false},<0.350.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]},2047,[{<<"capabilities">>,table,[{<<"publisher_confirms">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"basic.nack">>,bool,true},{<<"consumer_cancel_notify">>,bool,true},{<<"connection.blocked">>,bool,true},{<<"consumer_priorities">>,bool,true},{<<"authentication_failure_close">>,bool,true},{<<"per_consumer_qos">>,bool,true},{<<"direct_reply_to">>,bool,true}]},{<<"cluster_name">>,longstr,<<"rabbit@my-rabbit">>},{<<"copyright">>,longstr,<<"Copyright (c) 2007-2020 VMware, Inc. or its affiliates.">>},{<<"information">>,longstr,<<"Licensed under the MPL 2.0. Website: https://rabbitmq.com">>},{<<"platform">>,longstr,<<"Erlang/OTP 23.0.3">>},{<<"product">>,longstr,<<"RabbitMQ">>},{<<"version">>,longstr,<<"3.8.6">>}],none,false}
** Reason for termination ==
** socket_closed_unexpectedly
2020-12-22 18:42:03 =ERROR REPORT====
** Generic server <0.340.0> terminating 
** Last message in was socket_closed
** When Server state == {state,amqp_network_connection,{state,#Port<0.12>,<<"client 172.17.0.1:38375 -> 172.17.0.2:5672">>,10,<0.356.0>,131072,<0.339.0>,undefined,false},<0.352.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]},2047,[{<<"capabilities">>,table,[{<<"publisher_confirms">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"basic.nack">>,bool,true},{<<"consumer_cancel_notify">>,bool,true},{<<"connection.blocked">>,bool,true},{<<"consumer_priorities">>,bool,true},{<<"authentication_failure_close">>,bool,true},{<<"per_consumer_qos">>,bool,true},{<<"direct_reply_to">>,bool,true}]},{<<"cluster_name">>,longstr,<<"rabbit@my-rabbit">>},{<<"copyright">>,longstr,<<"Copyright (c) 2007-2020 VMware, Inc. or its affiliates.">>},{<<"information">>,longstr,<<"Licensed under the MPL 2.0. Website: https://rabbitmq.com">>},{<<"platform">>,longstr,<<"Erlang/OTP 23.0.3">>},{<<"product">>,longstr,<<"RabbitMQ">>},{<<"version">>,longstr,<<"3.8.6">>}],none,false}
** Reason for termination ==
** socket_closed_unexpectedly
2020-12-22 18:42:03 =ERROR REPORT====
** Generic server <0.331.0> terminating 
** Last message in was socket_closed
** When Server state == {state,amqp_network_connection,{state,#Port<0.14>,<<"client 172.17.0.1:44033 -> 172.17.0.2:5672">>,10,<0.353.0>,131072,<0.330.0>,undefined,false},<0.348.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]},2047,[{<<"capabilities">>,table,[{<<"publisher_confirms">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"basic.nack">>,bool,true},{<<"consumer_cancel_notify">>,bool,true},{<<"connection.blocked">>,bool,true},{<<"consumer_priorities">>,bool,true},{<<"authentication_failure_close">>,bool,true},{<<"per_consumer_qos">>,bool,true},{<<"direct_reply_to">>,bool,true}]},{<<"cluster_name">>,longstr,<<"rabbit@my-rabbit">>},{<<"copyright">>,longstr,<<"Copyright (c) 2007-2020 VMware, Inc. or its affiliates.">>},{<<"information">>,longstr,<<"Licensed under the MPL 2.0. Website: https://rabbitmq.com">>},{<<"platform">>,longstr,<<"Erlang/OTP 23.0.3">>},{<<"product">>,longstr,<<"RabbitMQ">>},{<<"version">>,longstr,<<"3.8.6">>}],none,false}
** Reason for termination ==
** socket_closed_unexpectedly
2020-12-22 18:42:03 =ERROR REPORT====
** Generic server <0.328.0> terminating 
** Last message in was socket_closed
** When Server state == {state,amqp_network_connection,{state,#Port<0.10>,<<"client 172.17.0.1:33925 -> 172.17.0.2:5672">>,10,<0.357.0>,131072,<0.327.0>,undefined,false},<0.349.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]},2047,[{<<"capabilities">>,table,[{<<"publisher_confirms">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"basic.nack">>,bool,true},{<<"consumer_cancel_notify">>,bool,true},{<<"connection.blocked">>,bool,true},{<<"consumer_priorities">>,bool,true},{<<"authentication_failure_close">>,bool,true},{<<"per_consumer_qos">>,bool,true},{<<"direct_reply_to">>,bool,true}]},{<<"cluster_name">>,longstr,<<"rabbit@my-rabbit">>},{<<"copyright">>,longstr,<<"Copyright (c) 2007-2020 VMware, Inc. or its affiliates.">>},{<<"information">>,longstr,<<"Licensed under the MPL 2.0. Website: https://rabbitmq.com">>},{<<"platform">>,longstr,<<"Erlang/OTP 23.0.3">>},{<<"product">>,longstr,<<"RabbitMQ">>},{<<"version">>,longstr,<<"3.8.6">>}],none,false}
** Reason for termination ==
** socket_closed_unexpectedly
2020-12-22 18:42:03 =CRASH REPORT====
  crasher:
    initial call: amqp_gen_connection:init/1
    pid: <0.328.0>
    registered_name: []
    exception exit: {socket_closed_unexpectedly,[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,796}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.325.0>,amqp_sup,<0.298.0>]
    message_queue_len: 0
    messages: []
    links: [<0.325.0>]
    dictionary: [{gen_server_call_timeout,60000},{process_name,{amqp_gen_connection,<<"client 172.17.0.1:33925 -> 172.17.0.2:5672">>}}]
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 28
    reductions: 14160
  neighbours:
2020-12-22 18:42:03 =CRASH REPORT====
  crasher:
    initial call: amqp_gen_connection:init/1
    pid: <0.337.0>
    registered_name: []
    exception exit: {socket_closed_unexpectedly,[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,796}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.335.0>,amqp_sup,<0.298.0>]
    message_queue_len: 0
    messages: []
    links: [<0.335.0>]
    dictionary: [{gen_server_call_timeout,60000},{process_name,{amqp_gen_connection,<<"client 172.17.0.1:38357 -> 172.17.0.2:5672">>}}]
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 28
    reductions: 14165
  neighbours:
2020-12-22 18:42:03 =CRASH REPORT====
  crasher:
    initial call: amqp_gen_connection:init/1
    pid: <0.334.0>
    registered_name: []
    exception exit: {socket_closed_unexpectedly,[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,796}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.332.0>,amqp_sup,<0.298.0>]
    message_queue_len: 0
    messages: []
    links: [<0.332.0>]
    dictionary: [{gen_server_call_timeout,60000},{process_name,{amqp_gen_connection,<<"client 172.17.0.1:58109 -> 172.17.0.2:5672">>}}]
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 28
    reductions: 14160
  neighbours:
2020-12-22 18:42:03 =CRASH REPORT====
  crasher:
    initial call: amqp_gen_connection:init/1
    pid: <0.331.0>
    registered_name: []
    exception exit: {socket_closed_unexpectedly,[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,796}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.329.0>,amqp_sup,<0.298.0>]
    message_queue_len: 0
    messages: []
    links: [<0.329.0>]
    dictionary: [{gen_server_call_timeout,60000},{process_name,{amqp_gen_connection,<<"client 172.17.0.1:44033 -> 172.17.0.2:5672">>}}]
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 28
    reductions: 14168
  neighbours:
2020-12-22 18:42:03 =CRASH REPORT====
  crasher:
    initial call: amqp_gen_connection:init/1
    pid: <0.340.0>
    registered_name: []
    exception exit: {socket_closed_unexpectedly,[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,796}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.338.0>,amqp_sup,<0.298.0>]
    message_queue_len: 0
    messages: []
    links: [<0.338.0>]
    dictionary: [{gen_server_call_timeout,60000},{process_name,{amqp_gen_connection,<<"client 172.17.0.1:38375 -> 172.17.0.2:5672">>}}]
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 28
    reductions: 14162
  neighbours:
2020-12-22 18:42:03 =SUPERVISOR REPORT====
     Supervisor: {<0.325.0>,amqp_connection_sup}
     Context:    child_terminated
     Reason:     socket_closed_unexpectedly
     Offender:   [{pid,<0.328.0>},{name,connection},{mfargs,{amqp_gen_connection,start_link,[<0.327.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}]}},{restart_type,intrinsic},{shutdown,brutal_kill},{child_type,worker}]

2020-12-22 18:42:03 =SUPERVISOR REPORT====
     Supervisor: {<0.329.0>,amqp_connection_sup}
     Context:    child_terminated
     Reason:     socket_closed_unexpectedly
     Offender:   [{pid,<0.331.0>},{name,connection},{mfargs,{amqp_gen_connection,start_link,[<0.330.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}]}},{restart_type,intrinsic},{shutdown,brutal_kill},{child_type,worker}]

2020-12-22 18:42:03 =SUPERVISOR REPORT====
     Supervisor: {<0.325.0>,amqp_connection_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.328.0>},{name,connection},{mfargs,{amqp_gen_connection,start_link,[<0.327.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}]}},{restart_type,intrinsic},{shutdown,brutal_kill},{child_type,worker}]

2020-12-22 18:42:03 =SUPERVISOR REPORT====
     Supervisor: {<0.329.0>,amqp_connection_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.331.0>},{name,connection},{mfargs,{amqp_gen_connection,start_link,[<0.330.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}]}},{restart_type,intrinsic},{shutdown,brutal_kill},{child_type,worker}]

2020-12-22 18:42:03 =SUPERVISOR REPORT====
     Supervisor: {<0.335.0>,amqp_connection_sup}
     Context:    child_terminated
     Reason:     socket_closed_unexpectedly
     Offender:   [{pid,<0.337.0>},{name,connection},{mfargs,{amqp_gen_connection,start_link,[<0.336.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}]}},{restart_type,intrinsic},{shutdown,brutal_kill},{child_type,worker}]

2020-12-22 18:42:03 =SUPERVISOR REPORT====
     Supervisor: {<0.335.0>,amqp_connection_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.337.0>},{name,connection},{mfargs,{amqp_gen_connection,start_link,[<0.336.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}]}},{restart_type,intrinsic},{shutdown,brutal_kill},{child_type,worker}]

2020-12-22 18:42:03 =SUPERVISOR REPORT====
     Supervisor: {<0.338.0>,amqp_connection_sup}
     Context:    child_terminated
     Reason:     socket_closed_unexpectedly
     Offender:   [{pid,<0.340.0>},{name,connection},{mfargs,{amqp_gen_connection,start_link,[<0.339.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}]}},{restart_type,intrinsic},{shutdown,brutal_kill},{child_type,worker}]

2020-12-22 18:42:03 =SUPERVISOR REPORT====
     Supervisor: {<0.338.0>,amqp_connection_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.340.0>},{name,connection},{mfargs,{amqp_gen_connection,start_link,[<0.339.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}]}},{restart_type,intrinsic},{shutdown,brutal_kill},{child_type,worker}]

2020-12-22 18:42:03 =SUPERVISOR REPORT====
     Supervisor: {<0.332.0>,amqp_connection_sup}
     Context:    child_terminated
     Reason:     socket_closed_unexpectedly
     Offender:   [{pid,<0.334.0>},{name,connection},{mfargs,{amqp_gen_connection,start_link,[<0.333.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}]}},{restart_type,intrinsic},{shutdown,brutal_kill},{child_type,worker}]

2020-12-22 18:42:03 =SUPERVISOR REPORT====
     Supervisor: {<0.332.0>,amqp_connection_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.334.0>},{name,connection},{mfargs,{amqp_gen_connection,start_link,[<0.333.0>,{amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}]}},{restart_type,intrinsic},{shutdown,brutal_kill},{child_type,worker}]

2020-12-22 18:50:44 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.291.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},ok}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.290.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: [<0.290.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 28
    reductions: 201
  neighbours:
2020-12-22 18:51:23 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.291.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.CALC.Application',start,[normal,[]]},ok}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.290.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.292.0>,normal}]
    links: [<0.290.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 28
    reductions: 201
  neighbours:
